version: '3.7'

services: 
  service:
    restart: on-failure
    build: .
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
    volumes: 
      - ${HOME}/.goass/storage:/app/storage
    environment: 
      CONNECTION_STRING: 'root:root1234@tcp(db:3306)/goass'
      STORAGE_LOCATION: './.storage'
  
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes: 
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment: 
      MYSQL_ROOT_PASSWORD: 'root1234'