version: '3.7'

services: 
  service:
    restart: on-failure
    build: .
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
    volumes: 
      - ${HOME}/.goass/storage:/app/storage
    environment: 
      CONNECTION_STRING: 'postgresql://db:${DB_PORT}/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}'
      STORAGE_LOCATION: './storage'

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes: 
  postgres_data:
    