version: '3.7'

services: 
  service:
    restart: on-failure
    build: .
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
    volumes: 
      - ${HOME}/.goass/storage:/app/storage
    environment: 
      CONNECTION_STRING: 'mongodb://db:27017'
      STORAGE_LOCATION: './storage'
      API_ONLY: 'true'
  
  db:
    image: mongo:4.2.5
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/app/db

volumes: 
  mongodb_data_container:
    