version: '3.8'

services: 
  service_backend:
    restart: on-failure
    build: .
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
    volumes: 
      - ${HOME}/.goass/storage:/app/storage
    environment: 
      CONNECTION_STRING: 'postgresql://db:${DB_PORT}/${DB_NAME}?user=${DB_USER}&password=${DB_PASSWORD}'
      STORAGE_LOCATION: './storage'

  admin_backend:
    restart: on-failure
    build:
      context: ./admin/backend
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    links:
      - db
    depends_on:
      - db
    environment:
      APP_PORT: ${ADMIN_BACKEND_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}

  admin_frontend:
    restart: on-failure
    build:
      context: ./admin/frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${ADMIN_API_URL}
    ports:
      - 3000:80
    links:
      - admin_backend
    depends_on:
      - admin_backend

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes: 
  postgres_data:
  