CREATE DATABASE GOASS;

USE GOASS;

CREATE TABLE AUTHORS (
    ID BIGINT NOT NULL AUTO INCREMENT,
    NAME NVARCHAR(50),
    PRIMARY KEY(ID),
    CHECK(NAME <> "")
);

CREATE TABLE AUDIO (
    ID BIGINT NOT NULL AUTO INCREMENT,
    AUTHOR_ID BIGINT NOT NULL,
    TITLE NVARCHAR(50),
    PRIMARY KEY(ID),
    FOREIGN KEY(AUTHOR_ID)
        REFERENCES AUTHORS(ID)
);
